"""Initial migration

Revision ID: 04ab556e67d2
Revises: 
Create Date: 2026-01-21 08:36:32.257320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ab556e67d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('psc', sa.String(length=6), nullable=False),
    sa.Column('zprava', sa.Text(), nullable=True),
    sa.Column('datum_odeslani', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_submissions')
    # ### end Alembic commands ###
